"""Generates frontend/css/theme.css from the real theme_palettes data.

Python (theme_palettes.*) stays the single source of truth for color:
this module never hand-copies a hex value. Each palette becomes one
`html[data-theme="<slug>"] { --token: value; ... }` block using the mockup's
own custom-property names, so the ported CSS (app.css) needs no rework
beyond pointing at this generated file.

The mockup's --generated/--target/--flag semantics come from
glyph_quality's compare-mode coloring (a run's own output vs. the target
outline vs. a missed feature) and have no dedicated slot in the palette
token contract; success/info/danger are the closest existing semantic
tokens and stand in for them until Phase 1 wires real Compare-mode data.
"""
from __future__ import annotations

from pathlib import Path

from theme_palettes import DISPLAY_FONT_FAMILY, PALETTE_ORDER, PALETTES

# mockup CSS custom-property name -> theme_palettes palette key
_TOKEN_MAP = {
    "bg": "bg",
    "panel": "panel_alt",
    "panel-2": "entry_bg",
    "frame-light": "frame_light",
    "frame-dark": "frame_dark",
    "border": "border",
    "sash": "sash",
    "fg": "fg",
    "muted": "muted_fg",
    "disabled": "disabled_fg",
    "entry-bg": "entry_bg",
    "accent": "accent",
    "accent-active": "accent_active",
    "accent-glow": "accent_glow",
    "accent-fg": "select_fg",
    "generated": "success",
    "target": "info",
    "flag": "danger",
    "warn": "warn",
}

_FALLBACK_DISPLAY_FONT = '"Chakra Petch", "Segoe UI Semibold", sans-serif'


def _theme_block(slug: str) -> str:
    palette = PALETTES[slug]
    lines = [f'html[data-theme="{slug}"] {{']
    for css_var, palette_key in _TOKEN_MAP.items():
        lines.append(f"  --{css_var}: {palette[palette_key]};")
    display_family = DISPLAY_FONT_FAMILY.get(slug)
    if display_family:
        lines.append(f'  --display: "{display_family}", {_FALLBACK_DISPLAY_FONT};')
    else:
        lines.append(f"  --display: {_FALLBACK_DISPLAY_FONT};")
    lines.append("}")
    return "\n".join(lines)


def generate() -> str:
    header = (
        "/* Generated by tools/gen_modelbin_web/theme_export.py from the real\n"
        "   theme_palettes data -- do not hand-edit. Re-run theme_export.generate()\n"
        "   (or relaunch the web app) after changing a palette's PALETTE dict. */\n"
    )
    blocks = [_theme_block(slug) for slug in PALETTE_ORDER]
    return header + "\n\n".join(blocks) + "\n"


def write(out_path: Path) -> None:
    out_path.write_text(generate(), encoding="utf-8")


if __name__ == "__main__":
    write(Path(__file__).parent / "frontend" / "css" / "theme.css")
    print("wrote", Path(__file__).parent / "frontend" / "css" / "theme.css")
