"""ASCII-art import: place pasted ASCII art, character-for-character, using
one of the native in-game vinyl fonts (`forza_writer.shapes`) — never a font
generated by this tool or installed on the user's machine, since those would
need a second vinyl layer and wouldn't match what the in-game Vinyl Editor
itself can produce.

Coverage gap: the native vinyl fonts expose A-Z, a-z, all ten digits, and 18
symbols (`shapes.char_to_resource` is the source of truth — see
`supported_chars`; digit and symbol indices were corrected against a
verified KFPS glyph-mismatch report — see `shapes.py`'s module docstring).
Most ASCII-art punctuation still has no mapping (`.` `,` `'` `` ` `` `"` `~`
`-` `_` `<` `>` `*` `|` `(` `)` `[` `]` `{` `}` `\\` `=`) — see
`scan_unsupported`, which is how this module surfaces that gap instead of
guessing a substitute.

All 11 native font families share the exact same character coverage
(`char_to_resource` only changes which family a supported character comes
from, never which characters are supported) — so switching the font number
changes letterform style only. It is never a fix for an unsupported
character; only remapping it to a supported character, or leaving it blank,
is.

Unlike `layout.layout_forza_text` (variable per-character advance — a space
is narrower than a letter, an unsupported character narrower still), this
module lays out a strict fixed-pitch grid: every column advances by exactly
the same width and every row by exactly the same height, regardless of
whether that cell ends up with a glyph in it. That is what keeps a pasted
picture's columns aligned instead of drifting the way variable-width text
layout would.
"""

from __future__ import annotations

from forza_writer.layout import PIXEL_ART_SQUARE_SIZE
from forza_writer.shapes import char_to_resource, resource_to_shape_word, resource_to_typecode

DEFAULT_FONT = 1

# Printable ASCII plus the handful of Latin-1 symbols SYMBOL_MAP knows about
# (£ ¥ € æ Æ ß) — the full range char_to_resource is ever asked about, and
# so the complete set `supported_chars` needs to probe.
_CANDIDATE_CHARS = [chr(c) for c in range(0x21, 0x7F)] + list("£¥€æÆß")


def normalize_block(text: str) -> list[str]:
    """Split pasted text into a rectangular grid of equal-width rows.

    Right-pads every row with spaces to the block's longest line — a ragged
    paste (common when ASCII art is copied from a web page, where trailing
    spaces get trimmed unevenly) would otherwise shift later rows' columns
    out of alignment with earlier ones once placed on a fixed-pitch grid.
    Trailing blank lines (typically just the paste's final newline) are
    dropped rather than reserving a row for them.
    """
    lines = text.replace("\r\n", "\n").replace("\r", "\n").expandtabs(4).split("\n")
    while lines and lines[-1] == "":
        lines.pop()
    width = max((len(line) for line in lines), default=0)
    return [line.ljust(width) for line in lines]


def supported_chars(font: int = DEFAULT_FONT) -> set[str]:
    """Characters `font` can actually place, per `char_to_resource` — the
    single source of truth for native-font coverage (identical across all
    11 fonts; only the letterform style differs)."""
    return {c for c in _CANDIDATE_CHARS if char_to_resource(c, font) is not None}


def scan_unsupported(rows: list[str], font: int = DEFAULT_FONT) -> dict[str, list[tuple[int, int]]]:
    """Distinct characters in `rows` that `font` can't render, each mapped to
    every `(row, col)` it appears at. Space is never reported — it is always
    a valid, deliberately blank cell, not a missing glyph."""
    supported = supported_chars(font)
    locations: dict[str, list[tuple[int, int]]] = {}
    for row_index, row in enumerate(rows):
        for col_index, char in enumerate(row):
            if char == " " or char in supported:
                continue
            locations.setdefault(char, []).append((row_index, col_index))
    return locations


def layout_ascii_grid(
    rows: list[str],
    font: int = DEFAULT_FONT,
    cell_width: float = 18.0,
    cell_height: float = 25.0,
    remap: dict[str, str | None] | None = None,
    center_x: float = 0.0,
    center_y: float = 0.0,
    color: tuple[int, int, int, int] = (255, 255, 255, 255),
) -> list[dict]:
    """Place `rows` as a strict fixed-pitch grid of native-font glyphs.

    `cell_width`/`cell_height` are each cell's size in editor units, held
    constant across every column and row regardless of what (if anything)
    ends up in a given cell — that constancy, not the specific numbers, is
    what keeps the grid uniform. `remap` maps a source character to a
    replacement character, or to `None`/`" "` to force it blank; build it
    from `scan_unsupported` plus the user's own choices. A character with no
    `remap` entry and no `char_to_resource` mapping is simply left blank —
    never guessed at.
    """
    remap = remap or {}
    glyph_scale = cell_height * 0.82 / PIXEL_ART_SQUARE_SIZE
    total_height = len(rows) * cell_height

    shapes: list[dict] = []
    for row_index, row in enumerate(rows):
        total_width = len(row) * cell_width
        y = center_y - total_height / 2 + row_index * cell_height + cell_height / 2
        for col_index, char in enumerate(row):
            effective = remap.get(char, char)
            if effective in (None, " "):
                continue
            resource = char_to_resource(effective, font)
            if resource is None:
                continue
            x = center_x - total_width / 2 + col_index * cell_width + cell_width / 2
            family, index = resource
            shapes.append(
                {
                    "type": resource_to_typecode(family, index),
                    "type_word": resource_to_shape_word(family, index),
                    "data": [
                        round(x, 6),
                        round(-y, 6) or 0.0,
                        round(glyph_scale, 6),
                        round(glyph_scale, 6),
                        0.0,
                        0.0,
                        0,
                    ],
                    "color": list(color),
                }
            )
    return shapes
